#!/usr/bin/env bash
# Script to setup fresh Raspbian Lite installation as a kiosk with virtual keyboard
########

# Enable Autologin
raspi-config nonint do_boot_behaviour B2

# Install packages
apt-get update
apt-get install -y --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox matchbox-keyboard chromium-browser

# Setup chromium to start when X starts
cat << "EOF" > /etc/xdg/openbox/autostart
xset s off
xset s noblank
xset -dpms
matchbox-keyboard --daemon &
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --kiosk --touch-events=enabled --disable-pinch --noerrdialogs --disable-session-crashed-bubble --disable-infobars --app='$(cat /etc/kiosk_url)'
EOF

# Setup X to start at autologin
echo "startx -- -nocursor" >> /home/pi/.bash_profile
